package com.jarvis.calendarevent.domain.model.model.home.homedata

data class ItemX(
    val PR: Boolean,
    val all: List<All>,
    val artists: List<ArtistX>,
    val artistsNames: String,
    val banner: String,
    val cover: String,
    val description: String,
    val encodeId: String,
    val genreIds: List<String>,
    val isAlbum: Boolean,
    val isIndie: Boolean,
    val isPrivate: Boolean,
    val isShuffle: Boolean,
    val isSingle: Boolean,
    val isoffical: Boolean,
    val ispr: Int,
    val link: String,
    val others: List<Other>,
    val playItemMode: Int,
    val releaseDate: String,
    val sortDescription: String,
    val subType: Int,
    val target: String,
    val textType: String,
    val thumbnail: String,
    val thumbnailM: String,
    val title: String,
    val type: Int,
    val uid: Int,
    val userName: String,
    val vPop: List<VPop>
)